// Copyright (c) the go-ruby-tzinfo/tzinfo authors
//
// SPDX-License-Identifier: BSD-3-Clause

// Code generated from the tzinfo gem 2.0.6 (ZoneinfoDataSource over the
// system IANA zoneinfo iso3166.tab + zone1970.tab). DO NOT EDIT.

package tzinfo

// countryRecord is the raw data for one ISO-3166 country: its name and the
// ordered list of timezone identifiers observed within it (zone1970.tab order).
type countryRecord struct {
	name  string
	zones []string
}

// countryData maps an upper-case ISO-3166 alpha-2 code to its record.
var countryData = map[string]countryRecord{
	"AD": {name: "Andorra", zones: []string{"Europe/Andorra"}},
	"AE": {name: "United Arab Emirates", zones: []string{"Asia/Dubai"}},
	"AF": {name: "Afghanistan", zones: []string{"Asia/Kabul"}},
	"AG": {name: "Antigua & Barbuda", zones: []string{"America/Antigua"}},
	"AI": {name: "Anguilla", zones: []string{"America/Anguilla"}},
	"AL": {name: "Albania", zones: []string{"Europe/Tirane"}},
	"AM": {name: "Armenia", zones: []string{"Asia/Yerevan"}},
	"AO": {name: "Angola", zones: []string{"Africa/Luanda"}},
	"AQ": {name: "Antarctica", zones: []string{"Antarctica/McMurdo", "Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Mawson", "Antarctica/Palmer", "Antarctica/Rothera", "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok"}},
	"AR": {name: "Argentina", zones: []string{"America/Argentina/Buenos_Aires", "America/Argentina/Cordoba", "America/Argentina/Salta", "America/Argentina/Jujuy", "America/Argentina/Tucuman", "America/Argentina/Catamarca", "America/Argentina/La_Rioja", "America/Argentina/San_Juan", "America/Argentina/Mendoza", "America/Argentina/San_Luis", "America/Argentina/Rio_Gallegos", "America/Argentina/Ushuaia"}},
	"AS": {name: "Samoa (American)", zones: []string{"Pacific/Pago_Pago"}},
	"AT": {name: "Austria", zones: []string{"Europe/Vienna"}},
	"AU": {name: "Australia", zones: []string{"Australia/Lord_Howe", "Antarctica/Macquarie", "Australia/Hobart", "Australia/Melbourne", "Australia/Sydney", "Australia/Broken_Hill", "Australia/Brisbane", "Australia/Lindeman", "Australia/Adelaide", "Australia/Darwin", "Australia/Perth", "Australia/Eucla"}},
	"AW": {name: "Aruba", zones: []string{"America/Aruba"}},
	"AX": {name: "Åland Islands", zones: []string{"Europe/Mariehamn"}},
	"AZ": {name: "Azerbaijan", zones: []string{"Asia/Baku"}},
	"BA": {name: "Bosnia & Herzegovina", zones: []string{"Europe/Sarajevo"}},
	"BB": {name: "Barbados", zones: []string{"America/Barbados"}},
	"BD": {name: "Bangladesh", zones: []string{"Asia/Dhaka"}},
	"BE": {name: "Belgium", zones: []string{"Europe/Brussels"}},
	"BF": {name: "Burkina Faso", zones: []string{"Africa/Ouagadougou"}},
	"BG": {name: "Bulgaria", zones: []string{"Europe/Sofia"}},
	"BH": {name: "Bahrain", zones: []string{"Asia/Bahrain"}},
	"BI": {name: "Burundi", zones: []string{"Africa/Bujumbura"}},
	"BJ": {name: "Benin", zones: []string{"Africa/Porto-Novo"}},
	"BL": {name: "St Barthelemy", zones: []string{"America/St_Barthelemy"}},
	"BM": {name: "Bermuda", zones: []string{"Atlantic/Bermuda"}},
	"BN": {name: "Brunei", zones: []string{"Asia/Brunei"}},
	"BO": {name: "Bolivia", zones: []string{"America/La_Paz"}},
	"BQ": {name: "Caribbean NL", zones: []string{"America/Kralendijk"}},
	"BR": {name: "Brazil", zones: []string{"America/Noronha", "America/Belem", "America/Fortaleza", "America/Recife", "America/Araguaina", "America/Maceio", "America/Bahia", "America/Sao_Paulo", "America/Campo_Grande", "America/Cuiaba", "America/Santarem", "America/Porto_Velho", "America/Boa_Vista", "America/Manaus", "America/Eirunepe", "America/Rio_Branco"}},
	"BS": {name: "Bahamas", zones: []string{"America/Nassau"}},
	"BT": {name: "Bhutan", zones: []string{"Asia/Thimphu"}},
	"BV": {name: "Bouvet Island", zones: []string{}},
	"BW": {name: "Botswana", zones: []string{"Africa/Gaborone"}},
	"BY": {name: "Belarus", zones: []string{"Europe/Minsk"}},
	"BZ": {name: "Belize", zones: []string{"America/Belize"}},
	"CA": {name: "Canada", zones: []string{"America/St_Johns", "America/Halifax", "America/Glace_Bay", "America/Moncton", "America/Goose_Bay", "America/Blanc-Sablon", "America/Toronto", "America/Iqaluit", "America/Atikokan", "America/Winnipeg", "America/Resolute", "America/Rankin_Inlet", "America/Regina", "America/Swift_Current", "America/Edmonton", "America/Cambridge_Bay", "America/Inuvik", "America/Vancouver", "America/Creston", "America/Dawson_Creek", "America/Fort_Nelson", "America/Whitehorse", "America/Dawson"}},
	"CC": {name: "Cocos (Keeling) Islands", zones: []string{"Indian/Cocos"}},
	"CD": {name: "Congo (Dem. Rep.)", zones: []string{"Africa/Kinshasa", "Africa/Lubumbashi"}},
	"CF": {name: "Central African Rep.", zones: []string{"Africa/Bangui"}},
	"CG": {name: "Congo (Rep.)", zones: []string{"Africa/Brazzaville"}},
	"CH": {name: "Switzerland", zones: []string{"Europe/Zurich"}},
	"CI": {name: "Côte d’Ivoire", zones: []string{"Africa/Abidjan"}},
	"CK": {name: "Cook Islands", zones: []string{"Pacific/Rarotonga"}},
	"CL": {name: "Chile", zones: []string{"America/Santiago", "America/Coyhaique", "America/Punta_Arenas", "Pacific/Easter"}},
	"CM": {name: "Cameroon", zones: []string{"Africa/Douala"}},
	"CN": {name: "China", zones: []string{"Asia/Shanghai", "Asia/Urumqi"}},
	"CO": {name: "Colombia", zones: []string{"America/Bogota"}},
	"CR": {name: "Costa Rica", zones: []string{"America/Costa_Rica"}},
	"CU": {name: "Cuba", zones: []string{"America/Havana"}},
	"CV": {name: "Cape Verde", zones: []string{"Atlantic/Cape_Verde"}},
	"CW": {name: "Curaçao", zones: []string{"America/Curacao"}},
	"CX": {name: "Christmas Island", zones: []string{"Indian/Christmas"}},
	"CY": {name: "Cyprus", zones: []string{"Asia/Nicosia", "Asia/Famagusta"}},
	"CZ": {name: "Czech Republic", zones: []string{"Europe/Prague"}},
	"DE": {name: "Germany", zones: []string{"Europe/Berlin", "Europe/Busingen"}},
	"DJ": {name: "Djibouti", zones: []string{"Africa/Djibouti"}},
	"DK": {name: "Denmark", zones: []string{"Europe/Copenhagen"}},
	"DM": {name: "Dominica", zones: []string{"America/Dominica"}},
	"DO": {name: "Dominican Republic", zones: []string{"America/Santo_Domingo"}},
	"DZ": {name: "Algeria", zones: []string{"Africa/Algiers"}},
	"EC": {name: "Ecuador", zones: []string{"America/Guayaquil", "Pacific/Galapagos"}},
	"EE": {name: "Estonia", zones: []string{"Europe/Tallinn"}},
	"EG": {name: "Egypt", zones: []string{"Africa/Cairo"}},
	"EH": {name: "Western Sahara", zones: []string{"Africa/El_Aaiun"}},
	"ER": {name: "Eritrea", zones: []string{"Africa/Asmara"}},
	"ES": {name: "Spain", zones: []string{"Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"}},
	"ET": {name: "Ethiopia", zones: []string{"Africa/Addis_Ababa"}},
	"FI": {name: "Finland", zones: []string{"Europe/Helsinki"}},
	"FJ": {name: "Fiji", zones: []string{"Pacific/Fiji"}},
	"FK": {name: "Falkland Islands", zones: []string{"Atlantic/Stanley"}},
	"FM": {name: "Micronesia", zones: []string{"Pacific/Chuuk", "Pacific/Pohnpei", "Pacific/Kosrae"}},
	"FO": {name: "Faroe Islands", zones: []string{"Atlantic/Faroe"}},
	"FR": {name: "France", zones: []string{"Europe/Paris"}},
	"GA": {name: "Gabon", zones: []string{"Africa/Libreville"}},
	"GB": {name: "Britain (UK)", zones: []string{"Europe/London"}},
	"GD": {name: "Grenada", zones: []string{"America/Grenada"}},
	"GE": {name: "Georgia", zones: []string{"Asia/Tbilisi"}},
	"GF": {name: "French Guiana", zones: []string{"America/Cayenne"}},
	"GG": {name: "Guernsey", zones: []string{"Europe/Guernsey"}},
	"GH": {name: "Ghana", zones: []string{"Africa/Accra"}},
	"GI": {name: "Gibraltar", zones: []string{"Europe/Gibraltar"}},
	"GL": {name: "Greenland", zones: []string{"America/Nuuk", "America/Danmarkshavn", "America/Scoresbysund", "America/Thule"}},
	"GM": {name: "Gambia", zones: []string{"Africa/Banjul"}},
	"GN": {name: "Guinea", zones: []string{"Africa/Conakry"}},
	"GP": {name: "Guadeloupe", zones: []string{"America/Guadeloupe"}},
	"GQ": {name: "Equatorial Guinea", zones: []string{"Africa/Malabo"}},
	"GR": {name: "Greece", zones: []string{"Europe/Athens"}},
	"GS": {name: "South Georgia & the South Sandwich Islands", zones: []string{"Atlantic/South_Georgia"}},
	"GT": {name: "Guatemala", zones: []string{"America/Guatemala"}},
	"GU": {name: "Guam", zones: []string{"Pacific/Guam"}},
	"GW": {name: "Guinea-Bissau", zones: []string{"Africa/Bissau"}},
	"GY": {name: "Guyana", zones: []string{"America/Guyana"}},
	"HK": {name: "Hong Kong", zones: []string{"Asia/Hong_Kong"}},
	"HM": {name: "Heard Island & McDonald Islands", zones: []string{}},
	"HN": {name: "Honduras", zones: []string{"America/Tegucigalpa"}},
	"HR": {name: "Croatia", zones: []string{"Europe/Zagreb"}},
	"HT": {name: "Haiti", zones: []string{"America/Port-au-Prince"}},
	"HU": {name: "Hungary", zones: []string{"Europe/Budapest"}},
	"ID": {name: "Indonesia", zones: []string{"Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"}},
	"IE": {name: "Ireland", zones: []string{"Europe/Dublin"}},
	"IL": {name: "Israel", zones: []string{"Asia/Jerusalem"}},
	"IM": {name: "Isle of Man", zones: []string{"Europe/Isle_of_Man"}},
	"IN": {name: "India", zones: []string{"Asia/Kolkata"}},
	"IO": {name: "British Indian Ocean Territory", zones: []string{"Indian/Chagos"}},
	"IQ": {name: "Iraq", zones: []string{"Asia/Baghdad"}},
	"IR": {name: "Iran", zones: []string{"Asia/Tehran"}},
	"IS": {name: "Iceland", zones: []string{"Atlantic/Reykjavik"}},
	"IT": {name: "Italy", zones: []string{"Europe/Rome"}},
	"JE": {name: "Jersey", zones: []string{"Europe/Jersey"}},
	"JM": {name: "Jamaica", zones: []string{"America/Jamaica"}},
	"JO": {name: "Jordan", zones: []string{"Asia/Amman"}},
	"JP": {name: "Japan", zones: []string{"Asia/Tokyo"}},
	"KE": {name: "Kenya", zones: []string{"Africa/Nairobi"}},
	"KG": {name: "Kyrgyzstan", zones: []string{"Asia/Bishkek"}},
	"KH": {name: "Cambodia", zones: []string{"Asia/Phnom_Penh"}},
	"KI": {name: "Kiribati", zones: []string{"Pacific/Tarawa", "Pacific/Kanton", "Pacific/Kiritimati"}},
	"KM": {name: "Comoros", zones: []string{"Indian/Comoro"}},
	"KN": {name: "St Kitts & Nevis", zones: []string{"America/St_Kitts"}},
	"KP": {name: "Korea (North)", zones: []string{"Asia/Pyongyang"}},
	"KR": {name: "Korea (South)", zones: []string{"Asia/Seoul"}},
	"KW": {name: "Kuwait", zones: []string{"Asia/Kuwait"}},
	"KY": {name: "Cayman Islands", zones: []string{"America/Cayman"}},
	"KZ": {name: "Kazakhstan", zones: []string{"Asia/Almaty", "Asia/Qyzylorda", "Asia/Qostanay", "Asia/Aqtobe", "Asia/Aqtau", "Asia/Atyrau", "Asia/Oral"}},
	"LA": {name: "Laos", zones: []string{"Asia/Vientiane"}},
	"LB": {name: "Lebanon", zones: []string{"Asia/Beirut"}},
	"LC": {name: "St Lucia", zones: []string{"America/St_Lucia"}},
	"LI": {name: "Liechtenstein", zones: []string{"Europe/Vaduz"}},
	"LK": {name: "Sri Lanka", zones: []string{"Asia/Colombo"}},
	"LR": {name: "Liberia", zones: []string{"Africa/Monrovia"}},
	"LS": {name: "Lesotho", zones: []string{"Africa/Maseru"}},
	"LT": {name: "Lithuania", zones: []string{"Europe/Vilnius"}},
	"LU": {name: "Luxembourg", zones: []string{"Europe/Luxembourg"}},
	"LV": {name: "Latvia", zones: []string{"Europe/Riga"}},
	"LY": {name: "Libya", zones: []string{"Africa/Tripoli"}},
	"MA": {name: "Morocco", zones: []string{"Africa/Casablanca"}},
	"MC": {name: "Monaco", zones: []string{"Europe/Monaco"}},
	"MD": {name: "Moldova", zones: []string{"Europe/Chisinau"}},
	"ME": {name: "Montenegro", zones: []string{"Europe/Podgorica"}},
	"MF": {name: "St Martin (French)", zones: []string{"America/Marigot"}},
	"MG": {name: "Madagascar", zones: []string{"Indian/Antananarivo"}},
	"MH": {name: "Marshall Islands", zones: []string{"Pacific/Majuro", "Pacific/Kwajalein"}},
	"MK": {name: "North Macedonia", zones: []string{"Europe/Skopje"}},
	"ML": {name: "Mali", zones: []string{"Africa/Bamako"}},
	"MM": {name: "Myanmar (Burma)", zones: []string{"Asia/Yangon"}},
	"MN": {name: "Mongolia", zones: []string{"Asia/Ulaanbaatar", "Asia/Hovd"}},
	"MO": {name: "Macau", zones: []string{"Asia/Macau"}},
	"MP": {name: "Northern Mariana Islands", zones: []string{"Pacific/Saipan"}},
	"MQ": {name: "Martinique", zones: []string{"America/Martinique"}},
	"MR": {name: "Mauritania", zones: []string{"Africa/Nouakchott"}},
	"MS": {name: "Montserrat", zones: []string{"America/Montserrat"}},
	"MT": {name: "Malta", zones: []string{"Europe/Malta"}},
	"MU": {name: "Mauritius", zones: []string{"Indian/Mauritius"}},
	"MV": {name: "Maldives", zones: []string{"Indian/Maldives"}},
	"MW": {name: "Malawi", zones: []string{"Africa/Blantyre"}},
	"MX": {name: "Mexico", zones: []string{"America/Mexico_City", "America/Cancun", "America/Merida", "America/Monterrey", "America/Matamoros", "America/Chihuahua", "America/Ciudad_Juarez", "America/Ojinaga", "America/Mazatlan", "America/Bahia_Banderas", "America/Hermosillo", "America/Tijuana"}},
	"MY": {name: "Malaysia", zones: []string{"Asia/Kuala_Lumpur", "Asia/Kuching"}},
	"MZ": {name: "Mozambique", zones: []string{"Africa/Maputo"}},
	"NA": {name: "Namibia", zones: []string{"Africa/Windhoek"}},
	"NC": {name: "New Caledonia", zones: []string{"Pacific/Noumea"}},
	"NE": {name: "Niger", zones: []string{"Africa/Niamey"}},
	"NF": {name: "Norfolk Island", zones: []string{"Pacific/Norfolk"}},
	"NG": {name: "Nigeria", zones: []string{"Africa/Lagos"}},
	"NI": {name: "Nicaragua", zones: []string{"America/Managua"}},
	"NL": {name: "Netherlands", zones: []string{"Europe/Amsterdam"}},
	"NO": {name: "Norway", zones: []string{"Europe/Oslo"}},
	"NP": {name: "Nepal", zones: []string{"Asia/Kathmandu"}},
	"NR": {name: "Nauru", zones: []string{"Pacific/Nauru"}},
	"NU": {name: "Niue", zones: []string{"Pacific/Niue"}},
	"NZ": {name: "New Zealand", zones: []string{"Pacific/Auckland", "Pacific/Chatham"}},
	"OM": {name: "Oman", zones: []string{"Asia/Muscat"}},
	"PA": {name: "Panama", zones: []string{"America/Panama"}},
	"PE": {name: "Peru", zones: []string{"America/Lima"}},
	"PF": {name: "French Polynesia", zones: []string{"Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier"}},
	"PG": {name: "Papua New Guinea", zones: []string{"Pacific/Port_Moresby", "Pacific/Bougainville"}},
	"PH": {name: "Philippines", zones: []string{"Asia/Manila"}},
	"PK": {name: "Pakistan", zones: []string{"Asia/Karachi"}},
	"PL": {name: "Poland", zones: []string{"Europe/Warsaw"}},
	"PM": {name: "St Pierre & Miquelon", zones: []string{"America/Miquelon"}},
	"PN": {name: "Pitcairn", zones: []string{"Pacific/Pitcairn"}},
	"PR": {name: "Puerto Rico", zones: []string{"America/Puerto_Rico"}},
	"PS": {name: "Palestine", zones: []string{"Asia/Gaza", "Asia/Hebron"}},
	"PT": {name: "Portugal", zones: []string{"Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"}},
	"PW": {name: "Palau", zones: []string{"Pacific/Palau"}},
	"PY": {name: "Paraguay", zones: []string{"America/Asuncion"}},
	"QA": {name: "Qatar", zones: []string{"Asia/Qatar"}},
	"RE": {name: "Réunion", zones: []string{"Indian/Reunion"}},
	"RO": {name: "Romania", zones: []string{"Europe/Bucharest"}},
	"RS": {name: "Serbia", zones: []string{"Europe/Belgrade"}},
	"RU": {name: "Russia", zones: []string{"Europe/Kaliningrad", "Europe/Moscow", "Europe/Kirov", "Europe/Volgograd", "Europe/Astrakhan", "Europe/Saratov", "Europe/Ulyanovsk", "Europe/Samara", "Asia/Yekaterinburg", "Asia/Omsk", "Asia/Novosibirsk", "Asia/Barnaul", "Asia/Tomsk", "Asia/Novokuznetsk", "Asia/Krasnoyarsk", "Asia/Irkutsk", "Asia/Chita", "Asia/Yakutsk", "Asia/Khandyga", "Asia/Vladivostok", "Asia/Ust-Nera", "Asia/Magadan", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Kamchatka", "Asia/Anadyr"}},
	"RW": {name: "Rwanda", zones: []string{"Africa/Kigali"}},
	"SA": {name: "Saudi Arabia", zones: []string{"Asia/Riyadh"}},
	"SB": {name: "Solomon Islands", zones: []string{"Pacific/Guadalcanal"}},
	"SC": {name: "Seychelles", zones: []string{"Indian/Mahe"}},
	"SD": {name: "Sudan", zones: []string{"Africa/Khartoum"}},
	"SE": {name: "Sweden", zones: []string{"Europe/Stockholm"}},
	"SG": {name: "Singapore", zones: []string{"Asia/Singapore"}},
	"SH": {name: "St Helena", zones: []string{"Atlantic/St_Helena"}},
	"SI": {name: "Slovenia", zones: []string{"Europe/Ljubljana"}},
	"SJ": {name: "Svalbard & Jan Mayen", zones: []string{"Arctic/Longyearbyen"}},
	"SK": {name: "Slovakia", zones: []string{"Europe/Bratislava"}},
	"SL": {name: "Sierra Leone", zones: []string{"Africa/Freetown"}},
	"SM": {name: "San Marino", zones: []string{"Europe/San_Marino"}},
	"SN": {name: "Senegal", zones: []string{"Africa/Dakar"}},
	"SO": {name: "Somalia", zones: []string{"Africa/Mogadishu"}},
	"SR": {name: "Suriname", zones: []string{"America/Paramaribo"}},
	"SS": {name: "South Sudan", zones: []string{"Africa/Juba"}},
	"ST": {name: "Sao Tome & Principe", zones: []string{"Africa/Sao_Tome"}},
	"SV": {name: "El Salvador", zones: []string{"America/El_Salvador"}},
	"SX": {name: "St Maarten (Dutch)", zones: []string{"America/Lower_Princes"}},
	"SY": {name: "Syria", zones: []string{"Asia/Damascus"}},
	"SZ": {name: "Eswatini (Swaziland)", zones: []string{"Africa/Mbabane"}},
	"TC": {name: "Turks & Caicos Is", zones: []string{"America/Grand_Turk"}},
	"TD": {name: "Chad", zones: []string{"Africa/Ndjamena"}},
	"TF": {name: "French S. Terr.", zones: []string{"Indian/Kerguelen"}},
	"TG": {name: "Togo", zones: []string{"Africa/Lome"}},
	"TH": {name: "Thailand", zones: []string{"Asia/Bangkok"}},
	"TJ": {name: "Tajikistan", zones: []string{"Asia/Dushanbe"}},
	"TK": {name: "Tokelau", zones: []string{"Pacific/Fakaofo"}},
	"TL": {name: "East Timor", zones: []string{"Asia/Dili"}},
	"TM": {name: "Turkmenistan", zones: []string{"Asia/Ashgabat"}},
	"TN": {name: "Tunisia", zones: []string{"Africa/Tunis"}},
	"TO": {name: "Tonga", zones: []string{"Pacific/Tongatapu"}},
	"TR": {name: "Turkey", zones: []string{"Europe/Istanbul"}},
	"TT": {name: "Trinidad & Tobago", zones: []string{"America/Port_of_Spain"}},
	"TV": {name: "Tuvalu", zones: []string{"Pacific/Funafuti"}},
	"TW": {name: "Taiwan", zones: []string{"Asia/Taipei"}},
	"TZ": {name: "Tanzania", zones: []string{"Africa/Dar_es_Salaam"}},
	"UA": {name: "Ukraine", zones: []string{"Europe/Simferopol", "Europe/Kyiv"}},
	"UG": {name: "Uganda", zones: []string{"Africa/Kampala"}},
	"UM": {name: "US minor outlying islands", zones: []string{"Pacific/Midway", "Pacific/Wake"}},
	"US": {name: "United States", zones: []string{"America/New_York", "America/Detroit", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Indiana/Indianapolis", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Indiana/Marengo", "America/Indiana/Petersburg", "America/Indiana/Vevay", "America/Chicago", "America/Indiana/Tell_City", "America/Indiana/Knox", "America/Menominee", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/North_Dakota/Beulah", "America/Denver", "America/Boise", "America/Phoenix", "America/Los_Angeles", "America/Anchorage", "America/Juneau", "America/Sitka", "America/Metlakatla", "America/Yakutat", "America/Nome", "America/Adak", "Pacific/Honolulu"}},
	"UY": {name: "Uruguay", zones: []string{"America/Montevideo"}},
	"UZ": {name: "Uzbekistan", zones: []string{"Asia/Samarkand", "Asia/Tashkent"}},
	"VA": {name: "Vatican City", zones: []string{"Europe/Vatican"}},
	"VC": {name: "St Vincent", zones: []string{"America/St_Vincent"}},
	"VE": {name: "Venezuela", zones: []string{"America/Caracas"}},
	"VG": {name: "Virgin Islands (UK)", zones: []string{"America/Tortola"}},
	"VI": {name: "Virgin Islands (US)", zones: []string{"America/St_Thomas"}},
	"VN": {name: "Vietnam", zones: []string{"Asia/Ho_Chi_Minh"}},
	"VU": {name: "Vanuatu", zones: []string{"Pacific/Efate"}},
	"WF": {name: "Wallis & Futuna", zones: []string{"Pacific/Wallis"}},
	"WS": {name: "Samoa (western)", zones: []string{"Pacific/Apia"}},
	"YE": {name: "Yemen", zones: []string{"Asia/Aden"}},
	"YT": {name: "Mayotte", zones: []string{"Indian/Mayotte"}},
	"ZA": {name: "South Africa", zones: []string{"Africa/Johannesburg"}},
	"ZM": {name: "Zambia", zones: []string{"Africa/Lusaka"}},
	"ZW": {name: "Zimbabwe", zones: []string{"Africa/Harare"}},
}
